# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160310_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time_message_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
