# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_time_message_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-time_message_sent', 'name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
